workflows:
  android-build:
    name: Build APK Android
    environment:
      java: 17
    scripts:
      - name: Set execute permissions recursively
        script: |
          find . -type f -name "gradlew" -exec chmod +x {} \;
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build APK Release
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
