workflows:
  android-build:
    name: Build APK Android
    environment:
      vars:
        JAVA_VERSION: 17
      java: 17
    scripts:
      - name: Set Permission Gradlew
        script: |
          chmod +x ./gradlew
      - name: Clean Project
        script: |
          ./gradlew clean
      - name: Build APK Release
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - gustimanunggalgb@gmail.com
