workflows:
  android-workflow:
    name: Build APK Android via HP
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.godtv.app"
    scripts:
      - name: Set Gradlew Permissions
        script: chmod +x ./gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - build/**/outputs/apk/release/*.apk
