workflows:
  android-build:
    name: Build APK Android
    environment:
      java: 17
    scripts:
      - name: Force gradlew to be executable
        script: |
          chmod 777 ./gradlew
      - name: Clean project
        script: |
          sh ./gradlew clean
      - name: Build APK Release
        script: |
          sh ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
